version: "3"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASS}
      - POSTGRES_DB=${PGDB}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
  api:
    image: scottdkey/rollmein_api
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    command: bash -c 'while !/dev/tcp/database/5432; do sleep 1; done; yarn start'
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PGPASSWORD=${PGPASS}
      - PGUSER=${PGUSER}
      - PGPORT=${PGPORT}
      - PORT=${API_SERVER_PORT}
      - PGDATABASE=${PGDB}
      - REDIS_HOST=redis
      - PGHOST=database
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - database
      - redis
