version: "3"
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PGHOST=database
      - REDISHOST=redis
      - DEV_DB=${DEVELOPMENT_DATABASE}
      - TEST_DB=${TEST_DATABASE}
      - PROD_DB=${PRODUCTION_DATABASE}
      - BASE_URL=${API_BASE_URL}
      - SECRETKEY=${SECRETKEY}
      - PORT=${API_SERVER_PORT}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
  # web:
  #   build: ./web
  #   env_file:
  #     - .env
  #   ports:
  #     - ${WEB_APP_PORT}:${WEB_APP_ORIGIN}
  #   image: scottdkey/rollmein_web:1.0.0
  #   volumes:
  #     - .:/whiskeynight
  #   links:
  #     - api
  #   depends_on:
  #     - api
  #   restart: always
