version: "3.9"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - redis_data:/data
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/src:/usr/api/src
      - ./api/node_modules:/usr/api/node_modules
      - ./api/log:/usr/api/log
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
      - REDIS_HOST=redis
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - database
      - redis
  # frontend:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./web/src:/usr/app/src
  #     - ./web/node_modules:/usr/app/node_modules
  #     - .env:/usr/app/.env.local
  #   ports:
  #     - 3000:3000
  #   expose:
  #     - 3000
  #   depends_on:
  #     - api
  
volumes:
  postgres_db:
  redis_data:
