version: "3"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - PGUSER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
  api:
    depends_on:
      - database
      - redis
    image: scottdkey/rollmein_api
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/usr/app
    ports:
      - 5000:5000
    command: bash -c 'while !/dev/tcp/database/5432; do sleep 1; done; yarn dev'
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PGPASSWORD=${PGPASSWORD}
      - PGUSER=${PGUSER}
      - REDIS_HOST=redis
      - PGHOST=database
      - DEVELOPMENT_DATABASE=${DEVELOPMENT_DATABASE}
      - TEST_DATABASE=${TEST_DATABASE}
      - PRODUCTION_DATABASE=${PRODUCTION_DATABASE}
    expose:
      - 5000
  web:
    depends_on:
      - api
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:3000
    expose:
      - 3000
    image: scottdkey/rollmein_web
    volumes:
      - .:/whiskeynight
    links:
      - api
    depends_on:
      - api
    restart: always
