apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: backend
    namespace: rollmein
spec:
  type: ClusterIP
  selector:
    app: redis
    tier: backend
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
