apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollmein
  labels:
    app: rollmein
    tier: backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollmein
      tier: backend
  template:
    metadata:
      labels:
        app: rollmein
        tier: backend
    spec:
      containers:
        - name: rollmein
          image: scottdkey/rollmein_api:1.0.5
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
            - name: CORS_URL
              valueFrom:
                configMapKeyRef:
                  name: rollmein-config
                  key: CORS_URL
            - name: REDIS_HOST
              value: redis
            - name: SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: rollmein-secrets
                  key: SECRETKEY
            - name: PGHOST
              value: postgres
            - name: PGDB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_USER
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.4m"
            limits:
              memory: "512Mi"
              cpu: "0.8m"
