import { PlayerObject } from "../../types/Interfaces"

export const playersPlaceHolder: Array<PlayerObject> = [
  {
    name: "Emily",
    tank: false,
    dps: true,
    healer: true,
    locked: false,
    in: true,
    id: 1,
  },
  {
    name: "Tyler",
    tank: true,
    dps: true,
    healer: true,
    locked: false,
    in: true,
    id: 2,
  },
  {
    name: "Kevin",
    tank: true,
    dps: true,
    healer: false,
    locked: false,
    in: true,
    id: 3,
  },
  {
    name: "Jill",
    tank: false,
    dps: true,
    healer: true,
    locked: false,
    in: true,
    id: 4,
  },
  {
    name: "Scott",
    tank: false,
    dps: true,
    healer: true,
    locked: false,
    in: true,
    id: 5,
  },
  {
    name: "Jordan",
    tank: false,
    dps: true,
    healer: false,
    locked: false,
    in: true,
    id: 6,
  },
  {
    name: "Jason",
    tank: true,
    dps: true,
    healer: true,
    locked: false,
    in: true,
    id: 7,
  },
];
