version: "3.9"
name: rollmein
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - rollmein_db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - redis_data:/data
  api:
    container_name: api
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    volumes:
      - ../api/:/usr/app
    env_file:
      - .env
    environment:
      - PORT=8000
      - NODE_ENV=development
      - CORS_URL=http://localhost:3000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - WEBSOCKET_HOST=http://websocket
      - WEBSOCKET_PORT=8080
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - database
      - redis
      - websocket
  websocket:
    container_name: websocket
    build:
      context: ../websocket
      dockerfile: Dockerfile.dev
    volumes:
      - ../websocket/:/usr/app
    env_file:
      - .env
    environment:
      - PORT=8050
      - WEBSOCKET_PORT=8080
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - API_HOST=http://api:80
    ports:
      - 8050:8050
      - 8080:8080
    expose:
      - 80
      - 8080
    depends_on:
      - database
      - redis
  # frontend:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./web/src:/usr/app/src
  #     - ./web/node_modules:/usr/app/node_modules
  #     - .env:/usr/app/.env.local
  #   ports:
  #     - 3000:3000
  #   expose:
  #     - 3000
  #   depends_on:
  #     - api

volumes:
  rollmein_db:
  redis_data:
