import { PlayerObject } from "../../types/Interfaces"

export const playersPlaceHolder: Array<PlayerObject> = [
  {
    playerName: "Emily",
    tank: false,
    dps: true,
    healer: true,
    locked: false,
    inTheRoll: true,
    id: 1,
    userId: "placeHolder",
  },
  {
    playerName: "Tyler",
    tank: true,
    dps: true,
    healer: true,
    locked: false,
    inTheRoll: true,
    id: 2,
    userId: "placeHolder",
  },
  {
    playerName: "Kevin",
    tank: true,
    dps: true,
    healer: false,
    locked: false,
    inTheRoll: true,
    id: 3,
    userId: "placeHolder",
  },
  {
    playerName: "Jill",
    tank: false,
    dps: true,
    healer: true,
    locked: false,
    inTheRoll: true,
    id: 4,
    userId: "placeHolder",
  },
  {
    playerName: "Scott",
    tank: false,
    dps: true,
    healer: true,
    locked: false,
    inTheRoll: true,
    id: 5,
    userId: "placeHolder",
  },
  {
    playerName: "Jordan",
    tank: false,
    dps: true,
    healer: false,
    locked: false,
    inTheRoll: true,
    id: 6,
    userId: "placeHolder",
  },
  {
    playerName: "Jason",
    tank: true,
    dps: true,
    healer: true,
    locked: false,
    inTheRoll: true,
    id: 7,
    userId: "placeHolder",
  },
];
