apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollmein
    tier: frontend
  name: rollmein-fe
spec:
  type: ExternalName
  externalName: rollmein.vercel.app
  selector:
    app: rollmein
    teir: frontend
