apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollmein_fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollmein_fe
      tier: frontend
  template:
    metadata:
      labels:
        app: rollmein_fe
        tier: frontend
    spec:
      containers:
        - name: client
          image: scottdkey/rollmein_fe
          imagePullPolicy: "Always"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: rollmein_api
