apiVersion: v1
kind: Service
metadata:
  name: rollmein_fe
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    component: web
    app: rollmein
    tier: frontend
