apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: rollmein
    tier: backend
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: rollmein
      tier: backend
  template:
    metadata:
      labels:
        app: rollmein
        tier: backend
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
