apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    tier: backend
data:
  POSTGRES_DB: rollmein_prod
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: "5432"
  # this must be a sub directory of the mounted path
  # reference postgres.ss.yaml in the volumeMounts.mountPath
  PGDATA: /var/lib/postgresql/data/rollmeinData
