apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: postgres
    tier: backend
  ports:
    - port: 5432
      name: postgres
      targetPort: 5432
