apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rollmein
    tier: backend
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollmein
      tier: backend
  template:
    metadata:
      labels:
        app: rollmein
        tier: backend
    spec:
      containers:
        - name: api
          image: scottdkey/rollmein_api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: api-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
