apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollmein
    tier: backend
  name: rollmein-api
spec:
  type: NodePort
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: rollmein-api
    tier: backend
