apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollmein_api
    tier: backend
  name: api
spec:
  type: NodePort
  selector:
    app: rollmein_api
    tier: backend
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
      nodePort: 30036
