# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API_CI

on:
  workflow_run:
    workflows: ["API_Test"]
    types: [completed]

jobs:
  on-success:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6

      - name: Log into Docker Hub
        uses: docker/login-action@v1.9.0

        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: scottdkey/rollmein_api:latest, scottdkey/rollmein_api:${{ steps.short-sha.outputs.sha }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "Test suite was failed"
