apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-local-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  storageClassName: local-storage
  local:
    path: /data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker
  persistentVolumeReclaimPolicy: Retain
