apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
