apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: rollmein
    tier: backend
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: rollmein
      tier: backend
  template:
    metadata:
      labels:
        app: rollmein
        tier: backend
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
