apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    tier: backend
data:
  POSTGRES_DB: rollmein_prod
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: "5432"
  PGDATA: /var/lib/postgresql/data/pgdata
