apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollmein-api
  labels:
    app: rollmein-api
    tier: backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollmein-api
      tier: backend
  template:
    metadata:
      labels:
        app: rollmein-api
        tier: backend
    spec:
      containers:
        - name: api
          image: scottdkey/rollmein_api:1.0.3
          imagePullPolicy: Always
          env:
            - name: PGHOST
              value: postgres
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_PASSWORD
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: rollmein-api-config
                  key: PORT
            - name: NODE_ENV
              value: production
            - name: CORS_URL
              valueFrom:
                configMapKeyRef:
                  name: rollmein-api-config
                  key: CORS_URL
            - name: REDIS_HOST
              value: redis
            - name: SECRETKEY
              valueFrom:
                configMapKeyRef:
                  name: rollmein-api-config
                  key: SECRETKEY
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.4m"
            limits:
              memory: "512Mi"
              cpu: "0.8m"
